#!/bin/sh

no_changes () {
	git diff-index --quiet --cached HEAD --ignore-submodules -- &&
	git diff-files --quiet --ignore-submodules &&
	(test -z "$untracked" || test -z "$(untracked_files)")
}

list_files() {
    echo -n "     "
    git status | egrep '(modified:   |new file:   )' | cut -c12-
    echo
}

usage() {
    echo "usage: git paradox [options] commit"
    echo
}

up_until_folder() {
    gitfolder=`git rev-parse --git-dir`
    return $?
}

make_hook() {
    echo '#!/bin/sh
gitfolder=`git rev-parse --git-dir`
if test -e $gitfolder/.paradox
then
commit=`cat $gitfolder/.paradox | cut -c 1-7`..
contents=`cat $1`
echo "Time paradox: $commit is at the tip" > $gitfolder/.msgbuild
echo >> $gitfolder/.msgbuild
echo "$contents" >> $gitfolder/.msgbuild
cat $gitfolder/.msgbuild > $1
fi
' > $gitfolder/hooks/prepare-commit-msg
    chmod +x $gitfolder/hooks/prepare-commit-msg
}

if test $# -eq 0
then
    usage
    exit 1
fi

if no_changes
then
    git rm -r .
    git checkout $* .
    commit=`git rev-parse $*`
    checkout_commit=`git log | egrep "commit $commit" | awk '{ print $2 }'`
    up_until_folder
    make_hook
    echo $checkout_commit > $gitfolder/.paradox
    #if commit aborts, retrieve deleted files
    if ! git commit
    then
        git rm -rf .
        git checkout HEAD .
    fi
    rm $gitfolder/.paradox
    exit 0
fi

echo "error: Your local changes to the following files would be overwritten by the time paradox:"

list_files

echo "Please, commit your changes or stash them before you initiate a time paradox" 
echo "Aborting"

exit 1  
